-- 编制与账号种子。执行前必须：
--   SET @seed_password_hash = '${CCDS_SEED_PASSWORD_HASH}';
-- 哈希由运维用 CCDS_SEED_PASSWORD 在库外生成，禁止把明文口令写入本文件。
SET @seed_password_hash = IFNULL(NULLIF(@seed_password_hash, ''), 'SEED_HASH_UNSET');

INSERT INTO ccds_brigade (id, code, name) VALUES
    (1, 'longsha', '龙沙大队'),
    (2, 'tiefeng', '铁锋大队'),
    (3, 'jianhua', '建华大队'),
    (4, 'fularji', '富拉尔基大队'),
    (5, 'angangxi', '昂昂溪大队'),
    (6, 'meilisi', '梅里斯大队'),
    (7, 'nianzishan', '碾子山大队'),
    (8, 'longjiang', '龙江大队'),
    (9, 'yian', '依安大队'),
    (10, 'tailai', '泰来大队'),
    (11, 'gannan', '甘南大队'),
    (12, 'fuyu', '富裕大队'),
    (13, 'keshan', '克山大队'),
    (14, 'nehe', '讷河大队'),
    (15, 'kedong', '克东大队'),
    (16, 'baiquan', '拜泉大队');

INSERT INTO ccds_station (id, brigade_id, name, name_norm, category, sort_no) VALUES
    (1, 1, '安顺路消防站', '安顺路消防站', '消防站', 1),
    (2, 1, '海河路特勤站', '海河路特勤站', '特勤站', 2),
    (3, 1, '永安街消防站', '永安街消防站', '消防站', 3),
    (4, 1, '海山路消防站', '海山路消防站', '消防站', 4),
    (5, 2, '南树园消防站', '南树园消防站', '一级站', 5),
    (6, 2, '红旗路消防站', '红旗路消防站', '消防站', 6),
    (7, 3, '华溪消防站', '华溪消防站', '消防站', 7),
    (8, 3, '通北路消防站', '通北路消防站', '消防站', 8),
    (9, 4, '光明路消防站', '光明路消防站', '消防站', 9),
    (10, 4, '宝石消防站', '宝石消防站', '消防站', 10),
    (11, 5, '新兴消防站', '新兴消防站', '消防站', 11),
    (12, 6, '胜利消防站', '胜利消防站', '消防站', 12),
    (13, 7, '向华路消防站', '向华路消防站', '消防站', 13),
    (14, 8, '新明路消防站', '新明路消防站', '消防站', 14),
    (15, 9, '学府路消防站', '学府路消防站', '消防站', 15),
    (16, 10, '建设路消防站', '建设路消防站', '消防站', 16),
    (17, 11, '奋斗街消防站', '奋斗街消防站', '消防站', 17),
    (18, 12, '府右街消防站', '府右街消防站', '消防站', 18),
    (19, 13, '金鼎消防站', '金鼎消防站', '消防站', 19),
    (20, 14, '新和街消防站', '新和街消防站', '消防站', 20),
    (21, 15, '惠民街消防站', '惠民街消防站', '消防站', 21),
    (22, 16, '南城路消防站', '南城路消防站', '消防站', 22),
    (23, NULL, '战勤保障分队', '战勤保障分队', '战勤保障分队', 23);

INSERT INTO ccds_station_alias (station_id, alias) VALUES
    (7, '华溪消防救援站'),
    (23, '战勤保障站'),
    (14, '正阳路消防救援站'),
    (14, '正阳路消防站'),
    (14, '新明路消防救援站');

INSERT INTO ccds_account
    (username, password_hash, role, station_id, brigade_id, is_must_change_password)
VALUES
    ('qqhrzd', @seed_password_hash, 'hq', NULL, NULL, 1),
    ('kaifazhe', @seed_password_hash, 'developer', NULL, NULL, 1),
    ('lsdd', @seed_password_hash, 'brigade', NULL, 1, 1),
    ('tfdd', @seed_password_hash, 'brigade', NULL, 2, 1),
    ('jhdd', @seed_password_hash, 'brigade', NULL, 3, 1),
    ('fqdd', @seed_password_hash, 'brigade', NULL, 4, 1),
    ('aaxdd', @seed_password_hash, 'brigade', NULL, 5, 1),
    ('mlsdd', @seed_password_hash, 'brigade', NULL, 6, 1),
    ('nzsdd', @seed_password_hash, 'brigade', NULL, 7, 1),
    ('ljdd', @seed_password_hash, 'brigade', NULL, 8, 1),
    ('yadd', @seed_password_hash, 'brigade', NULL, 9, 1),
    ('tldd', @seed_password_hash, 'brigade', NULL, 10, 1),
    ('gndd', @seed_password_hash, 'brigade', NULL, 11, 1),
    ('fydd', @seed_password_hash, 'brigade', NULL, 12, 1),
    ('ksdd', @seed_password_hash, 'brigade', NULL, 13, 1),
    ('nhdd', @seed_password_hash, 'brigade', NULL, 14, 1),
    ('kddd', @seed_password_hash, 'brigade', NULL, 15, 1),
    ('bqdd', @seed_password_hash, 'brigade', NULL, 16, 1),
    ('aslxfz', @seed_password_hash, 'station', 1, 1, 1),
    ('hhltqz', @seed_password_hash, 'station', 2, 1, 1),
    ('yajxfz', @seed_password_hash, 'station', 3, 1, 1),
    ('hslxfz', @seed_password_hash, 'station', 4, 1, 1),
    ('nsyxfz', @seed_password_hash, 'station', 5, 2, 1),
    ('hqlxfz', @seed_password_hash, 'station', 6, 2, 1),
    ('hxxfz', @seed_password_hash, 'station', 7, 3, 1),
    ('tblxfz', @seed_password_hash, 'station', 8, 3, 1),
    ('gmlxfz', @seed_password_hash, 'station', 9, 4, 1),
    ('bsxfz', @seed_password_hash, 'station', 10, 4, 1),
    ('xxxfz', @seed_password_hash, 'station', 11, 5, 1),
    ('slxfz', @seed_password_hash, 'station', 12, 6, 1),
    ('xhlxfz', @seed_password_hash, 'station', 13, 7, 1),
    ('xmlxfz', @seed_password_hash, 'station', 14, 8, 1),
    ('xflxfz', @seed_password_hash, 'station', 15, 9, 1),
    ('jslxfz', @seed_password_hash, 'station', 16, 10, 1),
    ('fdjxfz', @seed_password_hash, 'station', 17, 11, 1),
    ('fyjxfz', @seed_password_hash, 'station', 18, 12, 1),
    ('jdxfz', @seed_password_hash, 'station', 19, 13, 1),
    ('xhjxfz', @seed_password_hash, 'station', 20, 14, 1),
    ('hmjxfz', @seed_password_hash, 'station', 21, 15, 1),
    ('nclxfz', @seed_password_hash, 'station', 22, 16, 1),
    ('zqbzfd', @seed_password_hash, 'station', 23, NULL, 1);
